### ISSUE TITLE
Spanish translation for "Horror Haunts a cabin in the woods".

### ISSUE THREAD

**Issue by vidimus** [Drake3/MOM#1]
Hello, @Drake3 

I've got in mind the translation into Spanish of your scenario. Is there any chance for updating the scenario with a possible Spanish translation?

Thanks.

**Comment by Drake3** [comment]
Hi vidimus,

not sure if this reply works. I had no idea that you can use github to 
send messages. Good job. If you want to do a spanish translation you are 
more than welcome!

Do you know how to do it?

You can send me the file to joedoevcb@gmail.com once you are done.

Thanks a lot!

Am 16.05.2020 um 21:37 schrieb vidimus:

**Comment by vidimus** [comment]
Hello, @Drake3 

Thanks for your offering. Don't worry, I've already translated seven scenarios.

I will contact you as soon as I start with the translation.

You're welcome!

**Comment by vidimus** [comment]
Hello, @Drake3 

Spanish translation for "Horror haunts a cabin in the woods" in on the way (half done already). I will post a new comment here with the file when I finish it.

**Comment by vidimus** [comment]
Hello, @Drake3 , the Spanish translation is ready. Let me know if you're available to sent you the file to update the scenario.

**Comment by Drake3** [comment]
Hello @vidimus, I am available to receive the file. Thanks for the effort!

**Comment by vidimus** [comment]
> Hello @vidimus, I am available to receive the file. Thanks for the effort!

Hello, @Drake3 . Today the file will be uploaded here and I will also send it to you by e-mail too.

And thanks to you for creating this enjoyable scenario!

**Comment by vidimus** [comment]
Here's the file:
[Localization.Spanish.txt](https://github.com/Drake3/MOM/files/4974629/Localization.Spanish.txt)

**Comment by Drake3** [comment]
It's uploaded.

**Comment by vidimus** [comment]
Great! Thanks a lot.

**Comment by vidimus** [comment]
Hello, @Drake3 
I've corrected some typos in the translation, not very important ones, but some users point me them so I have fixed them,
Would you mind to update the scenario with this new file?
[Localization.Spanish.txt](https://github.com/Drake3/MOM/files/5016391/Localization.Spanish.txt)


Besides, there's a bug on the scenario. When you kill the first Deep one hybrid, it drops a Brass key. But when Vanderbilt's ghost summons a new hybrid and you manage to eliminate it (the hybrid), again it drops the key and all the search tokens are newly triggered. And this situation is repeated every time that Vanderlbilt brings to the scenario a new Deep one hybrid monster.

**Comment by Drake3** [comment]
Its all updated and thanks for the bug report. Did not do a lot of development lately, since i got an arm injury.

**Comment by vidimus** [comment]
> Its all updated and thanks for the bug report. Did not do a lot of development lately, since i got an arm injury.

Thanks to you.
Sorry to hear about your arm. Hope you feel better!

**Comment by vidimus** [comment]
Hello, @Drake3 
I hope you fully recover from your arm injury.

1) I've revised the translation and I've corrected some bad spelled words.  Would you mind to update your scenario with this new translation version?

The update translation file is here:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/blob/master/El%20horror%20que%20acecha%20la%20caba%C3%B1a%20del%20bosque/Localization.Spanish.txt

2) Besides, one user put a comment on valkyrie feedback spreadsheet about a bug: the root cellar door disappears if you don't complete the puzzle.

**Comment by vidimus** [comment]
@Drake3, I saw the update but it's not working properly. It looks like the txt file is corrupted with hiden characters. I will fix it and resend it to you. 
I guess it's something related to the text writer I used for spelling check. A plain text editor will be used for the new file.

Sorry for the inconvenience.

**Comment by vidimus** [comment]
Here's the corrected file. I've tested and it works fine:

https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/5180084/Localization.Spanish.txt
