### ISSUE TITLE
Spanish translation: Horror haunts Main Street Market

### ISSUE THREAD

**Issue by vidimus** [Drake3/MOM#3]
Hello, @Drake3 

Probably in a few day I will start the Spanish translation of this scenario. Do you have any plans for updating or change something on the scenario? Just to know to start the translation or delay it until you make any changes.

**Comment by Drake3** [comment]
Thanks for the effort. There may be text remnants from the Cabin in the
Woods scenario in the scenario. Did you notice something like this.

Right now no changes are planned. So all should be well.

Am 06.12.2020 um 21:30 schrieb vidimus:

**Comment by vidimus** [comment]
Hello, @Drake3 . Thanks to you for the scenario.

My idea is to translate myself this scenario because I did it with the first part. I didn't started yet, but I will consult you any doubt in case they appear.

**Comment by vidimus** [comment]
By the way, @Drake3, did you receive a notification about this issue where I mentioned you? 

https://github.com/NPBruce/valkyrie/issues/1409#issue-757687340

A Russian translation is waiting for you!

**Comment by AVAvovan** [comment]
Well, i'm also translating this scenario right now. Things i noticed:
string 64: Return common item ""Magnifying Glass"". So may be in string 67 you should add: Receive common item ""Magnifying Glass"". Also in string 3 "Kown Issues" missed letter.
I hope it helps a little. Great scenario! I like dialogue options and consequences. And boss mechanics feels apropriate.

**Comment by vidimus** [comment]
Hello, @Drake3 . I'm planning in a short future to translate your other 2 scenarios "Main Street Market" and "Melinda". I'm quite busy right now, but maybe I can get some help to translate them, if you don't mind.

**Comment by vidimus** [comment]
Here's the translation (finally), @Drake3 
[Localization.Spanish.txt](https://github.com/Drake3/MOM/files/7070452/Localization.Spanish.txt)
I hope you could update the scenario with the Spanish version

**Comment by Drake3** [comment]
Thanks for the translation. Its uploaded.

**Comment by vidimus** [comment]
> Thanks for the translation. Its uploaded.

Hello, @Drake3 , the scenario has not been updated. Could you check it, please?

**Comment by Drake3** [comment]
Was an upload error. Should work now.

**Comment by vidimus** [comment]
> Was an upload error. Should work now.

Thanks! It's now online!. I´ll close this issue.
